# Generated by Django 4.2.4 on 2023-09-04 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RD_texting', '0003_campaign_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clients',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='age',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='city',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='email',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='campaign',
            name='ad_content',
            field=models.TextField(default='Default ad content'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ad_title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='age_group',
            field=models.CharField(default='Default Age Group', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_size',
            field=models.CharField(default='Default Audience Size', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='frequency_in_hours',
            field=models.PositiveIntegerField(default=24, help_text='Set the frequency in hours (e.g., 24 for once a day, 1 for once an hour).'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='email',
            field=models.CharField(default='example@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='phone_number',
            field=models.PositiveIntegerField(default=123456789),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(default='Default Location', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='region',
            field=models.CharField(default='Default Region', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(blank=True, default='Default Description', null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
