# Generated by Django 4.2.4 on 2023-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RD_texting', '0004_delete_clients_remove_campaign_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='email',
            field=models.CharField(default='example@example.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='phone_number',
            field=models.PositiveIntegerField(default=123456789, unique=True),
        ),
    ]
