# Generated by Django 4.2.4 on 2023-09-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RD_texting', '0006_remove_campaign_location_remove_uploadedfile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RD_texting.campaign'),
        ),
    ]
