# Generated by Django 4.2.4 on 2023-09-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RD_texting', '0007_alter_uploadedfile_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='campaign',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
